### ISSUE TITLE
Is there any message length or buffer size limit?

### ISSUE THREAD

**Issue by rebootcode** [oatpp/example-websocket#1]
Is there any message length or buffer size limit?

I want to send some of the "WebRTC" offer and answer "SDPDescription" among peers through WebSocket.

Can it handle big length message size?

**Comment by lganzzzo** [comment]
Hello @rebootcode ,

There is no message limits fo the message size. You may stream your message using multiple frames.

I will send you a code snippet (tomorrow or the day after tomorrow when I'll be available).

Meanwhile please take a look at the [WebSocket::sendOneFrame()](https://oatpp.io/api/latest/oatpp-websocket/WebSocket/#websocket-sendoneframe) method.

You may send messages of any size by splitting it into frames. Client will automatically reconstruct your message as for WebSocket protocol.  
You just have to pass correct FIN and OPCODE parameters to the above method.

Best Regards,
Leonid

**Comment by lganzzzo** [comment]
Hello @rebootcode ,

Currently the `rooms-server` example is capable to handle large messages. There is no limit on the message size. But you should take into account the fact that it stores the whole message in the memory - which may lead to a crash if someone send a huge file.

So if you want to reuse this code in your project you may want to reimplement this behaviour. For example stream message to temporary file(or other storage) and then downstream message to other clients from that file.

Regards,
Leonid

**Comment by rebootcode** [comment]
Got it! Thanks for this wonderful framework :)
