### ISSUE TITLE
[enhancement]broadcast messages to all clients?

### ISSUE THREAD

**Issue by surfingtomchen** [oatpp/example-websocket#2]
How to broadcast the same message that all the clients can receive? Do I need to implemented by a data structure to keep the clients information and monitor the close and open event each time client connected or disconnected?

**Comment by lganzzzo** [comment]
Hello @surfingtomchen ,

> Do I need to implemented by a data structure to keep the clients information and monitor the close and open event each time client connected or disconnected?

Yes. Basically that is what you need to do in order to send the same message to all clients.

You may also take a look at [rooms-chat example](https://github.com/oatpp/example-websocket/tree/master/async-server-rooms) - it is implemented with oatpp-async APIs which is a bit complicated... I'll recommend you to go with oatpp simple APIs first... but at least you can get the idea.

Regards,
Leonid

**Comment by surfingtomchen** [comment]
Thanks. I've noticed that rooms-chat example do helps and studying it.

**Comment by lganzzzo** [comment]
Please dont hesitate to ask questions. Async rooms exaple may be pretty tricky to understand in some places.

**Comment by surfingtomchen** [comment]
I find my self lost in the macros in AppComponents, how to access those members of the instance of appcomponent.

```c++
	/**
	*  Create websocket connection handler
	*/
	OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::network::server::ConnectionHandler>, websocketConnectionHandler)("websocket" /* qualifier */, [] {
		auto connectionHandler = oatpp::websocket::ConnectionHandler::createShared();
		connectionHandler->setSocketInstanceListener(std::make_shared<WSInstanceListener>());
		return connectionHandler;
	}());
```

for example

how to access the websocketConnectionHandler?

I've add following codes to the WSInstaceListener

```c++
/**
* Listener on new WebSocket connections.
*/
class WSInstanceListener : public oatpp::websocket::ConnectionHandler::SocketInstanceListener {
private:
	static constexpr const char* TAG = "Server_WSInstanceListener";

	std::map<v_int32, oatpp::websocket::WebSocket*> socketMap;

public:
	/**
	* Counter for connected clients.
	*/
	static std::atomic<v_int32> SOCKETS;
public:

	/**
	*  Called when socket is created
	*/
	void onAfterCreate(oatpp::websocket::WebSocket& socket, const std::shared_ptr<const ParameterMap>& params) override;

	/**
	*  Called before socket instance is destroyed.
	*/
	void onBeforeDestroy(const oatpp::websocket::WebSocket& socket) override;

	void addSocket(oatpp::websocket::WebSocket & socket);

	void removeSocket(v_int32 socketId);

	void broadcast(const oatpp::String & message);

};
```

how to call the broadcast function from the appcomponent?

**Comment by lganzzzo** [comment]
Hello @surfingtomchen ,

Treat `AppComponent` as an application config. It is a "toolset" that you application will use by injecting those components in different parts of your application. 
I the `AppComponent` you typically define things like: port to listen, object-mapper, client connections, number of threads to use, etc.
So you don't call broadcast function from the `AppComponent`

What I would do, is for example... Introduce 3rd object let's say `BroadcastManager` which knows about your `WSInstanceListener` and which calls `broadcast` method on some event - example timer event or whatever happen in your system.

Something like this.

P.S. You may also join the devs char here https://gitter.im/oatpp-framework/Lobby if you will.

Regards,
Leonid

**Comment by lganzzzo** [comment]
Closing this issue.
@surfingtomchen  please let me know if you have more questions.
