### ISSUE TITLE
AsyncWebSocket Client Example

### ISSUE THREAD

**Issue by gzhao12** [oatpp/example-websocket#4]
Hello,

I am trying to run an async websocket server and have a client send messages to the server using sendOneFrameTextAsync() from a separate project. I copied over the example async server from this repo and created an AsyncWebSocket in my client project which connects to the server successfully. The server looks like it's running properly because I am able to receive echos from the websocket.org echo test. However when I try to send a message from my client, the server does not receive anything. Stepping through the project it looks like when I call sendOneFrameTextAsync() in my client, the implementation of sendOneFrameAsync() in AsyncWebSocket.cpp is skipped and thus the message is not sent.

I'm not too familiar with asynchronous programming so I may just be missing something simple but any help would be greatly appreciated.

Thanks!

**Comment by lganzzzo** [comment]
Hello @gzhao12 ,

Please note that async methods should be called from within the coroutine.
The example you can find here - https://github.com/oatpp/benchmark-websocket/blob/master/client/src/ClientSocketListener.hpp#L103

Also, it would be helpful if you could post here your client code.

Best Regards,
Leonid

**Comment by gzhao12** [comment]
I apologize for the delay in my reply. I moved my async method calls into a Coroutine and managed to get them to work. Thank you very much for your help!

**Comment by lganzzzo** [comment]
Hey, nice to hear that!
Please let me know in case you have more questions!
